### ISSUE TITLE
katana frame hatası

### ISSUE THREAD

**Issue by HknMurat** [HackerAdana/hapentool#1]
selamlar yeni programınız hayırlı olsun blogtaki yazıya bakınca farkettim.

ilk hata bildirimide benden olsun ;D katana başarıyla yükleniyor ama sudo ktfconsole diyince aşağıdaki hatayı veriyor. 

```
Traceback (most recent call last):
  File "/usr/bin/ktfconsole", line 11, in <module>
    from core import Banner , Errors 
  File "/opt/HackerAdana/katana-framework/core/Banner.py", line 28, in <module>
    """+colors.HH+""" Modules """+colors.W+"""    [ """""+str(get_number_modules())+""" ] """+colors.HH+"""Tools """+colors.W+"""[ """+str(get_number_tools())+""" ]\n"""
  File "/opt/HackerAdana/katana-framework/core/Internal.py", line 354, in get_number_modules
    tree = ET.parse('core/modules.xml')
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: 'core/modules.xml'

```

**Comment by HackerAdana** [comment]
Merhaba, aşağıdaki komut ile çalıştırabilir musunuz?
`cd /opt/HackerAdana/katana-framework`
`sudo python ./ktf.console`

**Comment by HackerAdana** [comment]
Merhaba, İlgili düzenlemeyi yaptık lakin test etmediğimiz için geri aldık.

İlk olarak aşağıdaki komutu uçbirimde çalıştırın lütfen.
`sudo rm -rf /usr/bin/ktfconsole`
Ardından 0.3.1~beta sürümü ile yeniden kurulumu dener misiniz?

**Comment by HknMurat** [comment]
sorun düzelmiş. üstünden 3-4 sürüm geçmiş yeni deneyebildim sagolun çözüm için

**Comment by HackerAdana** [comment]
Hata bildirimi için biz teşekkür ederiz. Sorununuz çözüldüğüne göre başlığı kapatabiliriz
